### PR TITLE
Feat/dynamic palette size

### PR DESCRIPTION
**Pull request by martin-sweeny**
With this PR a user passes an object with some options as the second param, instead of just the type. The type is now one of the options, and included is an option for palette size.

The `paletteSize` option will control the number of swatches generated in the palette, the default being 5 (as it was).

### CODE REVIEW

**Comment by zeke** [comment]
Hey @martin-wiseweb. Just checking in again. Do you have time to update this PR?

**Comment by martin-sweeny** [comment]
@zeke Wow this got lost - so sorry!

If it's still relevant I can update this

**Comment by zeke** [comment]
Still relevant! Please do update this PR if you've got the time. Thanks for following up.

**Comment by martin-sweeny** [comment]
@zeke I updated the MR but noticed now - thanks to the conflict - you've already implemented the palette size feature.

Let me know how to proceed

**Comment by zeke** [comment]
Oops. Didn't realize someone had implemented that. Sorry about that.

The implementation, docs, and tests you've got here look great, so feel free to override the existing code in master with your new changes. Then I can merge this and release a new version.

**Comment by martin-sweeny** [comment]
Cool, I'll get to it this weekend

**Comment by zeke** [comment]
At long last, this is documented and released in `2.0.1`. See https://github.com/colorjs/get-image-colors/pull/20

Thanks for the help and patience y'all. 🤘

**Pull request closed without merging**
