### PR TITLE
Add support for any amount of colors

### PR DESCRIPTION
**Pull request by YouTwitFace**

### CODE REVIEW

**Comment by YouTwitFace** [comment]
Any updates? @dougmolineux @zeke

**Comment by zeke** [comment]
Hey sorry for not shipping this. I'm leaving the tab open and will get to it soon!

**Comment by zeke** [comment]
Yes! Haha.

Published it as a major to avoid breaking any existing users. Thanks again for this PR and for your patience. Happy new year to you too. 🎊 

```
~/git/colorjs/get-image-colors master
$ np major
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies using npm
 ✔ Running tests
 ✔ Bumping version using npm
 ✔ Publishing package
 ✔ Pushing tags

 get-image-colors 2.0.0 published 🎉
```

**Comment by YouTwitFace** [comment]
I don't think this should have caused any breaking changes.

**Comment by zeke** [comment]
@YouTwitFace you're probably right but I didn't rigorously review this change so I figured it's better to play it on the safe side and avoid accidentally affecting any existing users. Are you using the new version with success?

**Comment by ijambro** [comment]
How does this Pull Request "add support for any amount of colors"?  I see that the 5 is moved into the options object, but as a caller of get-image-colors, I still don't have a way to change the default of 5 colors requested?  I can pass an options object in myself, but it only uses this for "type", and still hard-codes 5 as the color count.

**Comment by YouTwitFace** [comment]
@ijambro it only uses the default 5 if you don't pass an object.

**Comment by ijambro** [comment]
Ah, you're right, of course.  I wasn't thinking of the case where an object was passed in for "options".

Tested locally and it works:
{ type: "image/jpg", count: 10 }

Can I improve the Readme to document that these options are available?

**Comment by YouTwitFace** [comment]
> Can I improve the Readme to document that these options are available?

I don't see why not, that would be great.

**Comment by zeke** [comment]
Yes please!

**Comment by ijambro** [comment]
I updated my Pull Request to add documentation of this capability in the Readme:
https://github.com/colorjs/get-image-colors/pull/20

**Pull request merged**
