### PR TITLE
Audit and update dependencies

### PR DESCRIPTION
**Pull request by AndrewLaneX**

### CODE REVIEW

**Comment by zeke** [comment]
Looks like checks are failing.

**Comment by AndrewLaneX** [comment]
Hmm, Node v4 doesn't support destructuring (mocha), Node v6 doesn't support async/await (also mocha), and Node v7 doesn't support the spreading objects (chokidar). :thinking:

**Comment by AndrewLaneX** [comment]
@zeke reminder :thinking:

**Comment by zeke** [comment]
> update Travis to test on newer versions of Node?

That sounds good 👍🏼

**Comment by zeke** [comment]
Thanks for the updates, @AndrewLaneX 👍🏼 

I published this as a new major version to be on the safe side for any existing users.

```
$ np major

  ✔ Prerequisite check
  ✔ Git
  ↓ Cleanup [skipped]
  ✔ Installing dependencies using npm
  ✔ Running tests using npm
  ✔ Bumping version using npm
  ✔ Publishing package using npm
  ✔ Pushing tags
  ✔ Creating release draft on GitHub

 get-image-colors 4.0.0 published 🎉
```

**Comment by AndrewLaneX** [comment]
Thanks!

**Pull request merged**
